[package]
name = "CursedRoll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwt-simple = "0.11.9"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true
